apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: {{ include "app.fullname" . }}
  name: {{ include "app.fullname" . }}
  namespace: {{ .Values.namespaceName }}
spec:
  tags:
    - from:
        kind: DockerImage
        name: "{{ .Values.image.registry }}/{{ .Values.image.projectName }}/{{ .Values.namespaceName }}:{{ .Values.image.tag}}"
      importPolicy:
        scheduled: {{ .Values.image.scheduledUpdate }}
      name: {{ .Values.image.tag }}
