apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}
type: Opaque
data:
  # Checks if the current operation is an "install" or an "upgrade".
  # This solution prevents the Secret from being overwritten during an upgrade.
  # It is adapted from: https://stackoverflow.com/a/64325744
  {{- if .Release.IsInstall }}
  # Set the PRIVATE_KEY to "TBD"
  PRIVATE_KEY: {{ "TBD" | b64enc }}
  {{ else }}
  # Retrieve the existing PRIVATE_KEY from the Secret and reuse it
  PRIVATE_KEY: {{ (lookup "v1" "Secret" .Release.Namespace (include "app.fullname" . )).data.PRIVATE_KEY }}
  {{ end }}