apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "app.fullname" . }}
  name: {{ include "app.fullname" . }}
  namespace: {{ .Values.namespaceName }}
spec:
  ports:
    - name: {{ .Values.service.portName }}
      port: {{ .Values.service.port }}
      protocol: {{ .Values.service.protocol }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ include "app.fullname" . }}
  type: {{ .Values.service.type }}
