apiVersion: v1
kind: Service
metadata:
  annotations: { }
  labels:
    sele.service: {{ .Values.service.name }}
  name: {{ include "app.fullname" . }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: {{ .Values.service.port.http.exposed }}
      targetPort: {{ .Values.service.port.http.target }}
  selector:
    sele.service: {{ .Values.service.name }}
